bcgov/TheOrgBook

- tob-web/Jenkinsfile
The test and prod deployments require input for the build to complete.  When you don't proceed with the deployments to test and prod the build shows as canceled, which is misleading when all you wanted to do was to deploy a successful build to dev and not to test or prod.
Deployment to test and prod are a separate concern.
> Remove test and prod deployments from the main Jenkins pipeline.

- tob-api/Jenkinsfile
Re-deploy schema-spy when the API changes so an related schema changes will be picked up.
> Re-deploy schema-spy when the API changes.

- openshift/initializeProjects.sh
- openshift/scripts/updatePolicy.sh
- tob-api/Jenkinsfile
- tob-web/Jenkinsfile
First pass at eliminating unnecessary builds and deployments.
Unfortunately the code contained in a Jenkins file is unable to affect the Pipeline's top level SCM settings to take advantage of the include and exclude filters that would stop the builds from being triggered.
We've taken steps at the next available level to short-circuit the build and avoid building anything if there were no changes in the context directory for the pipeline.  A 'build' still gets kicked off, but we avoid re-building and deploying things unnecessarily.
Plus;
- Updates to code documentation.
- Update initializeProjects scrip to grant Jenkins service account access to scale deployments.
> Update pipeline build process

- tob-api/api/urls.py
- tob-api/api/views_custom.py
- tob-api/tob_api/urls.py
- tob-api/tob_api/views.py
- moved the view and url into the api; route remains the same.
- refactored into a class to take advantage of the auto-generated api documentation.
> QuickLoad cleanup

- tob-api/api/claimProcesser.py
- The `name` field in claims is not always the same.
> Fix claim submission error.

- tob-api/api/search_serializers.py
- tob-api/api/search_views.py
- For endpoints that return more than one type in it's result set, group the results by type to make the results more digestible.
- Update the associated API documentation.
> Groups search results by type.

- tob-api/openshift/templates/schema-spy/schema-spy-deploy.json
- tob-db/openshift/schema-spy-oracle-deploy.dev.param
- tob-db/openshift/schema-spy-oracle-deploy.overrides.sh
- tob-db/openshift/schema-spy-oracle-deploy.param
- tob-db/openshift/schema-spy-oracle-deploy.prod.param
- tob-db/openshift/schema-spy-oracle-deploy.test.param
- tob-db/openshift/templates/Caddyfile
- tob-db/openshift/templates/schema-spy-oracle-deploy.json
- Update configuration template and settings
- Update params files.
- Add updated Caddyfile
- Create an override script to generate the config map and credentials.
- Switch to https
> Support for adding basic authentication to a SchemaSpy instance.

- tob-api/openshift/django-deploy.dev.param
- tob-api/openshift/django-deploy.param
- tob-api/openshift/django-deploy.prod.param
- tob-api/openshift/django-deploy.test.param
- tob-api/openshift/templates/django/django-deploy.json
- tob-api/openshift/templates/python-libindy/s2i/bin/run
Unwind the process and instance limitations imposed by the initial wallet implementation.
Now that we are using the enterprise wallet we don't need to;
- Have local storage for the wallet
- Limit the number of gunicorn (host) processes.
- Limit the number of tob-api instances.
> Unwind process and instance limitations

- docker/docker-compose.yml
- WEB_CONCURRENCY is used to control the number of gunicorn workers that get created.
The previous restrictions we had in place were equivalent to WEB_CONCURRENCY=1
When left undefined the scripts calculate the number of workers based on the
available resources.
> Add support for controlling the number of gunicorn workers

- docker/docker-compose.yml
- docker/manage
- Aligns with the deployment environments and allows for credentials to persist across restarts.
> Use the enterprise wallet by default.

- tob-api/openshift/django-deploy.bc-tob.dev.param
- tob-api/openshift/django-deploy.bc-tob.param
- tob-api/openshift/django-deploy.bc-tob.prod.param
- tob-api/openshift/django-deploy.bc-tob.test.param
- tob-api/openshift/django-deploy.dev.param
- tob-api/openshift/django-deploy.ontario.dev.param
- tob-api/openshift/django-deploy.ontario.param
- tob-api/openshift/django-deploy.ontario.prod.param
- tob-api/openshift/django-deploy.ontario.test.param
- tob-api/openshift/django-deploy.overrides.sh
- tob-api/openshift/django-deploy.param
- tob-api/openshift/django-deploy.prod.param
- tob-api/openshift/django-deploy.test.param
- tob-api/openshift/templates/django/django-deploy.json
- tob-web/openshift/angular-on-nginx-deploy.bc-tob.dev.param
- tob-web/openshift/angular-on-nginx-deploy.bc-tob.param
- tob-web/openshift/angular-on-nginx-deploy.bc-tob.prod.param
- tob-web/openshift/angular-on-nginx-deploy.bc-tob.test.param
- tob-web/openshift/angular-on-nginx-deploy.dev.param
- tob-web/openshift/angular-on-nginx-deploy.ontario.dev.param
- tob-web/openshift/angular-on-nginx-deploy.ontario.param
- tob-web/openshift/angular-on-nginx-deploy.ontario.prod.param
- tob-web/openshift/angular-on-nginx-deploy.ontario.test.param
- tob-web/openshift/angular-on-nginx-deploy.param
- tob-web/openshift/angular-on-nginx-deploy.prod.param
- tob-web/openshift/angular-on-nginx-deploy.test.param
- tob-web/openshift/templates/angular-on-nginx/angular-on-nginx-deploy.json
- When using simple basic authentication, configure the credentials on the API side and inject them into the client.  The client needs to be able to authenticate with the API in order to function.
> #338 - Refactor Client/API basic authorization configuration.

- docker/manage
- openshift/settings.bc-tob.sh
- openshift/settings.ontario.sh
- openshift/settings.sh
- tob-api/api_v2/urls.py
- tob-web/openshift/templates/nginx-runtime/s2i/bin/run
This works locally, but @WadeBarnes can you confirm there is nothing else required for open shift before this is merged?
This PR also adds a couple small adjustments:
- modifies the settings.sh files to fix a Mac specific issue
- adds some extra informational metadata to the swagger doc
Adresses #558, #566
> Update nginx conf to redirect /api/v2 to API deployment

- README.md
- SonarQube-Jenkinsfile
- Zap-Jenkinsfile
- Zap-Jenkinsfile.bc-tob.pipeline.param
- tob-web/Jenkinsfile
- Add a stand-alone Zap Scanning pipeline which preforms a baseline scan on the application once deployed to DEV.
- Performs scan and then publishes the results in SonarQube-Jenkinsfile
- Wire the Zap Scan into the tob-web pipeline
- The pipeline now waits for the deployment to complete and then triggers the Zap Scanning pipeline to perform an acrimonious scan.
- Also migrated the tob-web pipeline over to using the OpenShift Client Jenkins Plugin syntax.
- Add Zap quality badges to the ReadMe which link to the live reports in SonarQube.
> #603 - Integrate Zap Scanning

- tob-web/src/themes/bcgov/index.html
Remove Google Analytics and use Fathom instead - for BCGov theme
> Remove Google Analytics and use Fathom instead - for BCGov theme

- tob-web/package.json
Signed-off-by: Andrew Whitehead <cywolf@gmail.com>
> Restrict rxjs to version 6.3.x (6.4 requires a newer typescript version)

- tob-api/api_indy/management/commands/verify_credential_index.py
> Use internal URL by default for index verification.

- tob-web/src/app/cred/form.component.ts
- tob-web/src/app/cred/timeline.component.ts
In the timeline, hide credentials if:
- they have no effective date
- they have an invalid effective date
> Hide credentials in the timeline if they have no effective date

- tob-api/api_v2/models/Topic.py
- tob-api/api_v2/serializers/search.py
Removed filter that would cause no data to be returned when retrieving Topic attributes for schemas with description different than "Registration".
> Fixed topic attributes not displaying correctly on OrgBook UI

- tob-web/src/app/general-data.service.ts
- tob-web/src/app/util/attribute-list.component.ts
- tob-web/src/themes/default/util/attribute-list.component.html
Apart from a bit of noise introduced by the VSCode typescript formatter (I can go through and revert those changes, if deemed necessary), the changes include adding a function to `attribute-list.component` to pull the labels and display them, if available.
> Enable agent-defined claim labels

- tob-web/openshift/templates/nginx-runtime/s2i/bin/run
Fixes string replacement for names with multiple slashes, e.g. "API-SERVICE-NAME"
See https://stackoverflow.com/questions/5928156/replace-one-character-with-another-in-bash
Signed-off-by: Alejandro Sanchez <emailforasr@gmail.com>
> Replace all dashes with underscores in bash script

- docs/OrgBook-REST-Services.md
- openshift/certificate.conf
- tob-api/openshift/django-deploy.bc-tob.dev.param
- tob-api/openshift/django-deploy.bc-tob.param
- tob-api/openshift/django-deploy.bc-tob.test.param
- tob-db/openshift/postgresql-deploy.bc-tob.param
- tob-web/openshift/angular-on-nginx-deploy.bc-tob.dev.param
- tob-web/openshift/angular-on-nginx-deploy.bc-tob.param
- tob-web/openshift/angular-on-nginx-deploy.bc-tob.test.param
- tob-web/src/themes/bcgov/assets/config.json
Migrate OrgBook URLs to the `aries-vcr` instances.
> Migrate OrgBook URLs
