bcgov/TheOrgBook

- tob-api/api/fakedata.py
- tob-api/api/test_api_complex.py
- tob-api/api/test_api_custom.py
- tob-api/api/test_api_simple.py
Got everything to the point to where is it running and either passing (implemented), or skipping (not implemented).
> Update unit tests and test data.

- tob-api/openshift/templates/django-deploy.json
> Update api deployment configuration

- tob-api/tob_api/settings.py
Fake it into using https rather than http.
> Fix swagger UI

- tob-api/api/fakedata.py
- tob-api/api/test_api_complex.py
- tob-api/api/test_api_custom.py
- tob-api/api/test_api_simple.py
- tob-api/api/tests.py
- tob-api/openshift/generateBuilds.sh
- tob-api/openshift/generateDeployments.sh
- tob-api/test.bat
Used a bit of a hack and the generated sample data to get the complex unit tests working.
> Get the API unit tests working

- tob-web/Jenkinsfile
Try to eliminate build errors due to delayed tagging.
> Update pipeline configuration

- tob-api/api/search_indexes.py
- tob-api/api/search_serializers.py
- tob-api/api/search_views.py
- tob-api/api/templates/search/indexes/api/inactiveclaimreasonindex_text.txt
- tob-api/api/templates/search/indexes/api/issuerserviceindex_text.txt
- tob-api/api/templates/search/indexes/api/jurisdictionindex_text.txt
- tob-api/api/templates/search/indexes/api/locationindex_text.txt
- tob-api/api/templates/search/indexes/api/verifiedorgindex_text.txt
- tob-api/api/templates/search/indexes/api/voclaimtypeindex_text.txt
- tob-api/api/templates/search/indexes/api/vodoingbusinessasindex_text.txt
- tob-api/api/templates/search/indexes/api/volocationtypeindex_text.txt
- tob-api/api/templates/search/indexes/api/votypeindex_text.txt
- tob-api/api/urls.py
- tob-api/rebuildSearchIndex.bat
- tob-api/requirements.txt
- tob-api/tob-api.pyproj
- tob-api/tob_api/settings.py
Adds support for basic search on all datatype endpoints (excluding user management data).
> Initial search implementation

- tob-api/api/search_views.py
Indicate which fields can be used for searches.
> Add API documentation

- tob-api/api/urls.py
- tob-api/api/views_custom.py
- Endpoint to return the verified organization's 'Doing Business As' records.
- Endpoint to return the verified organization's Location records.
> Add API endpoints for verified organizations.

- .gitignore
- tob-solr/openshift/templates/solr-deploy.json
Add support for defining the core to be loaded.
Terminate the endpoint with TLS
> Update solr deployment configuration.

- tob-api/api/management/commands/migrate.py
- tob-api/openshift/generateDeployments.sh
- tob-api/openshift/scripts/configureDeployment.sh
- tob-api/openshift/templates/django-deploy.json
Wire up the API and search engine.
> Update deployment scripts

- DeployToTest-Jenkinsfile
- openshift/compBuilds.sh
- openshift/compDeployments.sh
- openshift/genBuilds.sh
- openshift/genDepls.sh
- openshift/settings.sh
- tob-api/openshift/pipeline.param
- tob-solr/openshift/pipeline.param
- tob-web/openshift/pipeline.param
- Fix a mac related issue in the scripts
- Allow the github webhook secret to get auto-generated.
- Add messages indicating which settings.sh files are being loaded.
- Add pipeline for deploying to TEST; this initial revision uses a brute force method to promote the application images from DEV to TEST.
> Updates scripts and pipeline parameters

- tob-api/api/claimProcesser.py
- tob-api/api/indy/claimParser.py
- tob-api/api/views.py
- Only deals with a single claim type; a 'Verified Organization' claim.
- Parses out and saves the organization and claim information to the database.
> Refine the claim parsing implementation

- .gitattributes
- docker/README.md
- docker/docker-compose.yml
- docker/manage.sh
- openshift/settings.sh
- tob-web/openshift/templates/angular-on-nginx/angular-on-nginx-build.json
- tob-web/openshift/templates/nginx-runtime/Dockerfile
Refer to the docker/README.md file for details on use and the current state of development.
> Initial docker compose implementation

- docker/README.md
- docker/docker-compose.yml
- docker/manage.sh
All services are now wired together and operational.
> Second docker compose iteration

- docker/manage.sh
- Add support for starting a select set of containers.
- Add support for redirecting tob-web to a specific api instance.
> Updates to docker compose management script

- openshift/settings.sh
- tob-api/api/claimDefProcesser.py
- tob-db/openshift/component.settings.sh
- tob-db/openshift/postgresql-deploy.overrides.sh
- tob-db/openshift/postgresql-oracle-fdw-build.param
- tob-db/openshift/postgresql-oracle-fdw-deploy.dev.param
- tob-db/openshift/postgresql-oracle-fdw-deploy.overrides.sh
- tob-db/openshift/postgresql-oracle-fdw-deploy.param
- tob-db/openshift/postgresql-oracle-fdw-deploy.prod.param
- tob-db/openshift/postgresql-oracle-fdw-deploy.test.param
- tob-db/openshift/schema-spy-oracle-fdw-deploy.dev.param
- tob-db/openshift/schema-spy-oracle-fdw-deploy.param
- tob-db/openshift/schema-spy-oracle-fdw-deploy.prod.param
- tob-db/openshift/schema-spy-oracle-fdw-deploy.test.param
- tob-db/openshift/templates/postgresql-oracle-fdw-build.json
- tob-db/openshift/templates/postgresql-oracle-fdw-deploy.json
- tob-db/openshift/templates/schema-spy-oracle-fdw-deploy.json
Add build and deployment settings and configuration for a ostgreSQL oracle-fdw container, and a schema-spy instance to document it.
> Add support for connecting to the registries database.

- tob-web/openshift/templates/angular-on-nginx/Dockerfile
- tob-web/src/themes/default/dashboard/dashboard.component.custom.scss
Testing still in progress, opening up PR to identify changes to get master branch working
> Fix master, updates to new theme components

- tob-api/api/__init__.py
- tob-api/api/apps.py
- tob-api/api/claimDefProcesser.py
- tob-api/api/claimProcesser.py
- tob-api/api/eventloop.py
- tob-api/api/indy/agent.py
- tob-api/api/indy_views.py
- tob-api/api/proofRequestProcesser.py
- tob-api/openshift/templates/libindy/Dockerfile
- tob-api/requirements.txt
Updated branch to latest version of indy-sdk and von_agent
Pointed build to bcgov repositories for indy-sdk and von_agent
Use virtual wallet to filter claims
Other bug fixes
> Tob master fix

- tob-api/api/indy/agent.py
- tob-api/tob_api/settings.py
Do not require WALLET_SEED during build process.
> Fix for broken API interface build.

- docker/manage
- Stop and remove project specific containers as needed
- Only remove project related volumes
> Update the functionality of the rm management command.

- docker/README.md
- docker/manage
- Add support for registering DIDs with a provisional ledger.
- Update the VON Network quick start guide.
> Docker manage script updates

- tob-solr/openshift/solr-deploy.bc-tob.dev.param
- tob-solr/openshift/solr-deploy.bc-tob.param
- tob-solr/openshift/solr-deploy.bc-tob.prod.param
- tob-solr/openshift/solr-deploy.bc-tob.test.param
- tob-solr/openshift/solr-deploy.dev.param
- tob-solr/openshift/solr-deploy.ontario.dev.param
- tob-solr/openshift/solr-deploy.ontario.param
- tob-solr/openshift/solr-deploy.ontario.prod.param
- tob-solr/openshift/solr-deploy.ontario.test.param
- tob-solr/openshift/solr-deploy.param
- tob-solr/openshift/solr-deploy.prod.param
- tob-solr/openshift/solr-deploy.test.param
- tob-solr/openshift/templates/solr-deploy.json
- Remove the external route to Solr, effectively turning into an internal backend service for the tob-api.
> #338 - Remove external access to Solr.

- tob-web/openshift/templates/nginx-runtime/s2i/bin/run
- Basic auth is not compatible with the tob-api just yet.
> #338 - Update nginx proxy configuration.

- tob-web/src/themes/ongov/home/home.component.html
- tob-web/src/themes/ongov/search/input.component.html
> update ongov theme to support new search paradigm and functional paging

- tob-api/api_v2/serializers/search.py
- tob-api/api_v2/views/rest.py
> Filter topic related fields by revoked false

- tob-api/buildSolrSuggester.sh
- tob-api/updateSearchIndex.sh
- Fix `-b` switch on update and rebuild.
- Add simple helper for building the Suggester until we can do something more fancy.
> Updated Solr helper scripts

- openshift/manage
- Add support for individually scaling pods.
- Update the hard reset process to support the new postgres wallet implementation.
- Remove the did registration command.  TOB registers itself with our ledgers.
> Update manage script

- docker/manage
- tob-api/api_v2/indy/credential.py
- tob-api/api_v2/management/commands/reprocess_credentials.py
> Adds a django management command to reprocess all credentials with latest config

- docs/CLI-README.md
Signed-off-by: Stephen Curran <swcuran@gmail.com>
> Update the CLI Readme with publishing to SLN directions

- APISpec/openapi.yml
> Restore the Open API spec

- openshift/manage
- Add commands to manage the Solr index and core.
> Add management commands

- README.md
- ResettingTheLedger.md
- RunningLocal.md
- docker/README.md
Signed-off-by: Stephen Curran <swcurran@gmail.com>
> Updates to the readme and other MD files

- README.md
- ResettingTheLedger.md
- docker/README.md
- openshift/manage
- tob-web/src/themes/default/assets/recipes/start_a_restaurant.json
Signed-off-by: Stephen Curran <swcurran@gmail.com>
> Updating references to the renamed Permitify to dFlow repo

- README.md
- docker/README.md
Signed-off-by: Stephen Curran <swcurran@gmail.com>
> Change from permitify to dFlow

- tob-web/src/themes/bcgov/index.html
> Add Google Analytics support

- tob-web/src/themes/bcgov/home/home.component.html
> Updated BCGov homepage

- tob-web/src/themes/bcgov/index.html
Workaround to limit analytics to BC ToB prod site.
> Workaround to limit analytics to BC ToB prod site.

- tob-web/openshift/templates/nginx-runtime/nginx.conf.template
- tob-web/src/themes/bcgov/index.html
Add support for adding deployment-specific Fathom tracker.
> Add support for adding deployment-specific Fathom tracker.

- tob-web/src/themes/bcgov/index.html
> Add Matomo tracking snippet to BCGov theme.

- tob-api/tob_api/custom_settings_ongov.py
Signed-off-by: Ivan Wei <ivan.wei@ontario.ca>
> Ontario-centric message in swagger header

- tob-api/api_v2/utils.py
Facilitates more finely grained site monitoring.
> #772 - Add count for registrations in the last 24h

- tob-api/api_v2/models/Topic.py
> Fix issue with Topic relation fields

- tob-web/package.json
Bumped bootstrap version to address vulnerability.
> Bumped bootstrap version.

- tob-api/api_indy/tob_anchor/solrqueue.py
- tob-api/api_v2/search/index.py
- tob-api/api_v2/utils.py
- tob-api/api_v2/views/misc.py
- Determine whether or not they are synced.
> Perform a quick check on the indexes

- openshift/manage
> Add `indexSynced` command

- tob-api/Jenkinsfile
- tob-db/Jenkinsfile
- tob-solr/Jenkinsfile
- tob-web/Jenkinsfile
- Fix failed waiting for build to start issue.
>  Fix failed waiting for build to start issue. (#3)

- tob-api/api_indy/management/commands/verify_credential_index.py
- tob-api/requirements.txt
- tob-api/tob_api/rocketchat_hooks.py
- tob-api/verifyIndexes.sh
> Add tools to verify indexes.

- tob-api/api_indy/management/commands/verify_credential_index.py
- Add support for inactive and revoked credentials.
> Update index verification tools

- openshift/manage
- Calculate difference when indexes are our of sync.
> Update openshift/manage script

- docker/manage
- tob-api/api_indy/tob_anchor/solrqueue.py
- tob-api/api_v2/search/index.py
> Add additional logging to indexing processes

- tob-api/api_indy/tob_anchor/solrqueue.py
- Turn off silently_fail for deletes too.
> #807 - Update Indexing Processes

- tob-api/api_indy/tob_anchor/solrqueue.py
> Check if queue is empty on exit.

- tob-api/api_indy/tob_anchor/solrqueue.py
> Update SolrQueue log levels

- tob-web/src/app/data-types.ts
> Fix credential page for relationship credentials

- docker/manage
> Add restart option to manage script

- tob-api/api_v2/views/rest.py
> Updated swagger auto docs

- tob-api/api_v2/views/rest.py
> Fix API routes and align swagger spec to API behavior

- README.md
- docs/OrgBook-REST-Services.md
> Added overview of API's

- tob-api/openshift/schema-spy-deploy.overrides.sh
- tob-backup/openshift/backup-deploy.overrides.sh
- tob-web/openshift/angular-on-nginx-deploy.overrides.sh
> Fix issues locating config files

- openshift/settings.sh
> Remove unused settings

- openshift/certificate.conf
> Fix route references in certificate.conf

- tob-web/openshift/templates/nginx-runtime/Dockerfile
> Fix file and folder permissions on nginx-runtime

- tob-web/openshift/templates/angular-on-nginx/angular-on-nginx-deploy.json
> Extend route timeout

- tob-web/openshift/templates/nginx-runtime/s2i/bin/run
> Make API rate limit adjustable.

- tob-web/openshift/angular-on-nginx-deploy.bc-tob.dev.param
- tob-web/openshift/angular-on-nginx-deploy.bc-tob.param
- tob-web/openshift/angular-on-nginx-deploy.bc-tob.prod.param
- tob-web/openshift/angular-on-nginx-deploy.bc-tob.test.param
- tob-web/openshift/templates/angular-on-nginx/angular-on-nginx-deploy.json
> Add API rate limit settings.

- APISpec/openapi.yml
- tob-api/api_v2/views/search.py
- tob-api/tob_api/inspector.py
- tob-api/tob_api/settings.py
Fixes swagger schema attributes for list results.
> Fix swagger schema for list results

- tob-web/src/themes/bcgov/assets/i18n/en.json
> Add descriptions for benefit companies

- openshift/manage
- tob-api/api_indy/management/commands/delete_topic.py
- tob-api/deleteTopic.sh
Added a manage script to delete a topic from orgbook.  Note that the Solr index is updated automatically based on django signals.  Wallet creds are not deleted (this will be added in the aries-vcr version of this command).
Openshift manage script is updated but not tested (not sure how to test on my local).
> manage script to delete a topic from orgbook

- tob-api/requirements.txt
> Fix error by pinning drf-yags dependency version
